version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
    - 8000:8000
    networks:
    - app-network
    restart: unless-stopped
  sdc-registration:
    build:
      context: .
      dockerfile: sdc-registration/Dockerfile
    ports:
    - 3001:3000
    networks:
    - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
